### ISSUE TITLE
Проблема со странами не СНГ

### ISSUE THREAD

**Issue by Khainaaeh** [PyluOtBabylu/Reborn-Stealer-2021-SOURCE#4]
С дедика находящегося в США не приходят логи, папка создаётся, стил проходит, значит проблема в отправке логов в телеграмме. И так, стрит юзать прокси или можно придумать чего?

**Comment by PyluOtBabylu** [comment]
Знакомый жаловался мол, телеграм начал вводить фильтр на отправку через апи, я думаю проблема в этом, тут наверное только панель спасет
